<?php /** @var $block \GetResponse\GetResponseIntegration\Block\Settings */?>

<?php
if (!$block->checkApiKey()) {
    return;
}

$forms = $block->getAllFormsFromGr();
$settings = $block->getWebformSettings();

?>
<style>
    .label {
        font-weight: bold;
    }

    .label label {
        display: inline-block;
    }

    td.label {
        vertical-align: top;
    }

    .value input {
        margin-top: 4px;
        width: 100%;
    }

    .note {
        color: #303030;
        font-size: 12px;
        margin-top: 5px;
    }

    .admin__scope-old input[type="checkbox"] {
        -moz-appearance: checkbox;
    }

    tr {
        margin-bottom: 5px;
    }
</style>

<div>
    <p>
        You can now add your GetResponse web forms to your Magento store. Simply pick one of the web forms you’ve
        created at GetResponse and choose the location to insert the web form.
    </p>
</div>

<form method="post" action="<?php echo $block->getUrl('getresponseintegration/settings/webformpost'); ?>">
    <?php echo $block->getBlockHtml('formkey'); ?>
        <table class="config admin__scope-old">
            <tbody>
            <tr>
                <td class="label" style="width:200px;">
                    <label for="publish" style="margin-top: 7px;">Publish</label>
                </td>
                <td class="value">
                    <select name="publish" id="publish">
                        <option value="0">Off</option>
                        <option value="1"<?php if (isset($settings['active_subscription']) && $settings['active_subscription'] == 1): ?> selected="selected"<?php endif; ?>>On</option>
                    </select>
                    <p class="note">
                    <span>
                        Select if you want to publish your webform in magento.
                    </span>
                    </p>
                </td>
            </tr>

            <tr class="forms"
                <?php
                if (!isset($settings['active_subscription']) || $settings['active_subscription'] != 1) {
                    echo ' style="display: none;"';
                }
                ?>
            >
                <td class="label">
                    <label for="webform_id" style="margin-top: 7px;">Web Form:</label>
                </td>
                <td class="value">
                    <select name="webform_id" id="webform_id">
                        <?php
                        if (!empty($forms['forms']) || !empty($forms['webforms'])) {
                            if (isset($forms['forms']) && count($forms['forms']) > 0) {
                                echo '<option value="" disabled="disabled">New Forms:</option>';
                                foreach ($forms['forms'] as $form) {
                                    echo '<option value="' . $form->webformId . '" data-url="' . $form->scriptUrl . '"';
                                    echo (isset($settings['webform_id']) && $settings['webform_id'] == $form->webformId) ? ' selected="selected"' : '';
                                    echo '>' . $form->name . '</option>';
                                }
                            }

                            if (!empty($forms['webforms'])) {
                                echo '<option value="" disabled="disabled">Old Web Forms:</option>';
                                foreach ($forms['webforms'] as $form) {
                                    echo '<option value="' . $form->webformId . '" data-url="' . $form->scriptUrl . '"';
                                    echo (isset($settings['webform_id']) && $settings['webform_id'] == $form->webformId) ? ' selected="selected"' : '';
                                    echo '>' . $form->name . '</option>';
                                }
                            }
                        } else {
                            echo '<option value="" disabled="disabled">No forms</option>';
                        }
                        ?>
                    </select>
                    <input type="hidden" value="" name="webform_url" id="webform_url" />
                    <p class="note">
                    <span>
                        Select a Webform you would like to publish.
                    </span>
                    </p>
                </td>
            </tr>

            <tr class="forms"
                <?php
                if (!isset($settings['active_subscription']) || $settings['active_subscription'] != 1) {
                    echo ' style="display: none;"';
                }
                ?>
            >
                <td class="label">
                    <label for="sidebar" style="margin-top: 7px;">Web Form position:</label>
                </td>
                <td class="value">
                    <select name="sidebar">
                        <?php $positions = ['content' => 'Content Top', 'page.bottom' => 'Content Bottom', 'footer-container' => 'Footer', 'sidebar.main' => 'Sidebar Top', 'div.sidebar.additional' => 'Sidebar Bottom'];
                        foreach ($positions as $position => $name) {
                            echo '<option value="' . $position . '"';
                            if (isset($settings['sidebar']) && $position == $settings['sidebar']) echo ' selected="selected"';
                            echo '>' . $name . '</option>';
                        }
                        ?>
                    </select>
                    <p class="note">
                    <span>
                        Select a block in which you want webform to be placed.
                    </span>
                    </p>
                </td>
            </tr>

            </tbody>
        </table>
    <button id="export" title="Export" type="submit" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false">
        <span class="ui-button-text">
            <span>Save settings</span>
        </span>
    </button>
</form>

<script>
    var sod = jQuery('#publish'), forms = jQuery('.forms'), webform_id = jQuery('#webform_id'), webform_url = jQuery('#webform_url');
    if (sod.prop('checked') == true) {
        forms.show();
    }
    sod.change(function () {
        forms.toggle('slow');
    });
    webform_url.val(webform_id.find(':selected').attr('data-url'));
    webform_id.change(function() {
        webform_url.val(webform_id.find(':selected').attr('data-url'));
    });
</script>